[package]
name = "dev-board"
version = "0.1.0"
authors = ["Jonas Schievink <jonasschievink@gmail.com>"]
edition = "2018"
publish = false
description = "Dev-Board support crate"

[dependencies]
mcp2210 = "0.1.0"
embedded-hal = "0.2.3"
log = "0.4.8"
spi-memory = { path = ".." }
bitflags = "1.2.1"
