[package]
name = "bringup"
version = "0.1.0"
authors = ["Jonas Schievink <jonasschievink@gmail.com>"]
edition = "2018"
description = "Interactive development board bringup assistant"

[dependencies]
mcp2210 = "0.1.0"
